
export const GET_TRENDING_INIT = 'GET_TRENDING_INIT';
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS';
export const GET_TRENDING_FAIL = 'GET_TRENDING_FAIL';

export const SEARCH_INIT = 'SEARCH_INIT';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const ADD_REMOVE_FAVORITE = 'ADD_REMOVE_FAVORITE';

export const SEARCH_FAVORITES = 'SEARCH_FAVORITES';
